# Linkedin
username: # Email Address
password: # Account Password

positions:
- DevOps
# - Another position you want to search for
# - A third position you want to search for

locations:
- London
# - Amsterdam
# - The Hague

# NOTE This funciton inputs to the upload function.
#      The upload function is currently broken. 
#      As a work around the script will select the most recent uploaded/used CV on linkedin
uploads:
  Resume: # ./Users/{USER}/Desktop/AutoLinkedin/bot/CVDocument.pdf
# A second location you want to search in

# --------- Optional Parameters -------
# uploads:
#  Resume: # PATH TO Resume
#  Cover Letter: # PATH TO cover letter
#  Photo: # PATH TO photo


# output_filename:
# - # PATH TO OUTPUT FILE (default output.csv)

blacklist:
# - # Company names you want to ignore

#blackListTitles:
#- # Add job titles / Words you want to ignore

blackListTitles:
# Keywords
